/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This enum describes available Token types. ## Examples ``` # use cosmwasm_std::Addr; # use astroport::asset::AssetInfo::{NativeToken, Token}; Token { contract_addr: Addr::unchecked("terra...") }; NativeToken { denom: String::from("uluna") }; ```
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: Addr;
        [k: string]: unknown;
      };
    }
  | {
      native_token: {
        denom: string;
        [k: string]: unknown;
      };
    };
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;

/**
 * This structure describes a migration message.
 */
export interface MigrateMsg {
  /**
   * The blocked list of tokens
   */
  blocked_list_tokens?: AssetInfo[] | null;
  /**
   * The Factory address
   */
  factory?: string | null;
  /**
   * Contract address which can only set active generators and their alloc points
   */
  generator_controller?: string | null;
  /**
   * The limit of generators
   */
  generator_limit?: number | null;
  /**
   * The guardian address
   */
  guardian?: string | null;
  /**
   * The voting escrow contract
   */
  voting_escrow?: string | null;
  /**
   * Whitelist code id
   */
  whitelist_code_id?: number | null;
  [k: string]: unknown;
}
