/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg =
  | {
      config: {
        [k: string]: unknown;
      };
    }
  | {
      state: {
        time_seconds?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      reward_info: {
        staker_addr: string;
        time_seconds?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      all_reward_infos: {
        limit?: number | null;
        start_after?: string | null;
        time_seconds?: number | null;
        [k: string]: unknown;
      };
    };
