/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes the callback messages of the contract.
 */
export type CallbackMsg =
  | {
      optimal_swap: {
        [k: string]: unknown;
      };
    }
  | {
      provide_liquidity: {
        receiver: string;
        [k: string]: unknown;
      };
    };
