/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  from_timestamp?: number | null;
  merkle_roots?: string[] | null;
  owner?: string | null;
  to_timestamp: number;
  token_address: string;
  [k: string]: unknown;
}
