/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes the execute messages of the contract.
 */
export type ExecuteMsg =
  | {
      update_config: {
        /**
         * Contract address to send governance fees to (the Maker)
         */
        fee_address?: string | null;
        /**
         * Contract address where Lp tokens can be auto_staked after someone provides liquidity in an incentivized Astroport pool
         */
        generator_address?: string | null;
        /**
         * CW20 token contract code identifier
         */
        token_code_id?: number | null;
        /**
         * CW1 whitelist contract code id used to store 3rd party rewards for staking Astroport LP tokens
         */
        whitelist_code_id?: number | null;
        [k: string]: unknown;
      };
    }
  | {
      update_pair_config: {
        /**
         * New [`PairConfig`] settings for a pair type
         */
        config: PairConfig;
        [k: string]: unknown;
      };
    }
  | {
      create_pair: {
        /**
         * The two assets to create the pool for
         */
        asset_infos: [AssetInfo, AssetInfo];
        /**
         * Optional binary serialised parameters for custom pool types
         */
        init_params?: Binary | null;
        /**
         * The pair type (exposed in [`PairType`])
         */
        pair_type: PairType;
        [k: string]: unknown;
      };
    }
  | {
      deregister: {
        /**
         * The assets for which we deregister a pool
         */
        asset_infos: [AssetInfo, AssetInfo];
        [k: string]: unknown;
      };
    }
  | {
      propose_new_owner: {
        /**
         * The date after which this proposal expires
         */
        expires_in: number;
        /**
         * Newly proposed contract owner
         */
        owner: string;
        [k: string]: unknown;
      };
    }
  | {
      drop_ownership_proposal: {
        [k: string]: unknown;
      };
    }
  | {
      claim_ownership: {
        [k: string]: unknown;
      };
    };
/**
 * This enum describes available pair types. ## Available pool types ``` # use astroport::factory::PairType::{Custom, Stable, Xyk}; Xyk {}; Stable {}; Custom(String::from("Custom")); ```
 */
export type PairType =
  | {
      xyk: {
        [k: string]: unknown;
      };
    }
  | {
      stable: {
        [k: string]: unknown;
      };
    }
  | {
      custom: string;
    };
/**
 * This enum describes available Token types. ## Examples ``` # use cosmwasm_std::Addr; # use astroport::asset::AssetInfo::{NativeToken, Token}; Token { contract_addr: Addr::unchecked("terra...") }; NativeToken { denom: String::from("uluna") }; ```
 */
export type AssetInfo =
  | {
      token: {
        contract_addr: Addr;
        [k: string]: unknown;
      };
    }
  | {
      native_token: {
        denom: string;
        [k: string]: unknown;
      };
    };
/**
 * A human readable address.
 *
 * In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.
 *
 * This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.
 *
 * This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance.
 */
export type Addr = string;
/**
 * Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.
 *
 * This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>
 */
export type Binary = string;

/**
 * This structure stores a pair type's configuration.
 */
export interface PairConfig {
  /**
   * ID of contract which is allowed to create pairs of this type
   */
  code_id: number;
  /**
   * Whether a pair type is disabled or not. If it is disabled, new pairs cannot be created, but existing ones can still read the pair configuration
   */
  is_disabled: boolean;
  /**
   * Setting this to true means that pairs of this type will not be able to get an ASTRO generator
   */
  is_generator_disabled: boolean;
  /**
   * The amount of fees (in bps) collected by the Maker contract from this pair type
   */
  maker_fee_bps: number;
  /**
   * The pair type (provided in a [`PairType`])
   */
  pair_type: PairType;
  /**
   * The total fees (in bps) charged by a pair of this type
   */
  total_fee_bps: number;
  [k: string]: unknown;
}
