/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure describes a custom struct to return a query response containing the base contract configuration.
 */
export interface ConfigResponse {
  /**
   * The Astroport factory contract address
   */
  astroport_factory: string;
  [k: string]: unknown;
}
