/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This structure holds the parameters used for creating a contract.
 */
export interface InstantiateMsg {
  /**
   * The astroport factory contract address
   */
  astroport_factory: string;
  [k: string]: unknown;
}
