/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InstantiateMsg {
  ib_token_code_id: number;
  owner: string;
  protocol_admin_address: string;
  protocol_rewards_collector_address: string;
  [k: string]: unknown;
}
